---
openapi: 3.0.0
info:
  title: Nexus API
  version: 1.0.0
  description: API documentation for the Nexus application
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /healthcheck:
    get:
      summary: Check service health
      operationId: checkHealth
      responses:
        '200':
          description: API is healthy
        '500':
          description: Internal server error

  /login:
    post:
      summary: User login
      operationId: loginUser
      requestBody:
        description: Login credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /logout:
    post:
      summary: User logout
      operationId: logoutUser
      responses:
        '204':
          description: Successful logout
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /change-password:
    post:
      summary: Change user password
      operationId: changePassword
      requestBody:
        description: Password change request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: Password changed successfully
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid current password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          example: "user1"
        password:
          type: string
          example: "password123"

    LoginResponse:
      type: object
      properties:
        redirect_url:
          type: string
          example: "/"
        match:
          type: boolean
          example: true
        cookie:
          type: string
          example: "session_id_value"

    ChangePasswordRequest:
      type: object
      properties:
        current_password:
          type: string
          example: "currentPassword123"
        new_password:
          type: string
          example: "newPassword456"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid request"
